name: rich_string_parser
description: A dart string parser for parsing multible different formats.
version: 1.0.1
homepage: https://github.com/richie-south/dart-string-parser
author: richard soderman <richard.soderman@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
